### ISSUE TITLE
Redaction issue: email address on PDF

### ISSUE THREAD

**Issue by anniejw6** [JoshData/crs-reports-website#13]
On the PDF version of [this report](https://www.everycrsreport.com/reports/R43244.html) (link to [pdf](https://www.everycrsreport.com/files/20180508_R43244_27641671f850c14b441f6f543b96731949baae7f.pdf)), the email redaction does not seem to be working properly. On page 23, even though the text of the email is redacted, the second author's email is still displayed as an embedded link (e.g., if you hover over the text).

Looking at a few other reports, this issue seems to be uncommon but not unique (see, e.g., page 12 of [this report](https://www.everycrsreport.com/reports/R44762.html)).

**Comment by JoshData** [comment]
Thanks for reporting this issue! (cc @DanielSchuman)

We hadn't realized that the reports contain links, and our automated redaction tool (which I created for this project) didn't support redacting links. I've take a first step and updated our tool to also be able to redact links (bd5827b77479458323efd8b5f36bb5d1ca4e12f2) and I will shortly update everycrsreport to make use of that, and I'll have to re-run the redactor on all of the reports to fix already-published files.

I'll update this issue when I've done that.

Thanks again.

**Comment by JoshData** [comment]
I'm still re-redacting some of the PDFs we publish, but I think I've gotten most of them that might have embedded links, so I'm closing this issue. Thanks again!
