### ISSUE TITLE
Website in repository description is missing www

### ISSUE THREAD

**Issue by anand-bhat** [JoshData/crs-reports-website#2]
The website in the repository description (https://EveryCRSReport.com) does not open. It should probably be changed to https://www.EveryCRSReport.com if there isn't a plan to redirect non-www to www.

![image](https://cloud.githubusercontent.com/assets/7332442/19616117/fa1901e2-9828-11e6-9e1a-9f6e18f7f693.png)

![image](https://cloud.githubusercontent.com/assets/7332442/19616134/3020de04-9829-11e6-9086-57e0d70da109.png)

**Comment by JoshData** [comment]
Fixed, thanks! We don't have a way to do a redirect on https yet.
