### ISSUE TITLE
links from reports to other reports could be rewritten

### ISSUE THREAD

**Issue by JoshData** [JoshData/crs-reports-website#3]
In the HTML, CRS reports often link to other CRS reports (e.g. to "http://www.crs.gov/Reports/98-747"). These links could be replaced with their equivalent URLs on our site.

**Comment by DanielSchuman** [comment]
I'm fine with that. If we're going to look at the html, it also may be useful to have the citations to the US code link to the US Code (using the pre-built parser) or the statutes (which are all available online at legislink.)
